name: ci

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup .NET 5
        uses: actions/setup-checkout@v1
	  with:
           dotnet-version:'5.0.x'
      -
        name: Restore dependencies
        run: dotnet restore
      -
        name: Build app
        run: dotnet build -c Release --no-restore
        
